"""Adicionando password_hash

Revision ID: 927da4765d76
Revises: 863704e3d790
Create Date: 2025-04-03 18:58:21.607790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927da4765d76'
down_revision = '863704e3d790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
